/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package doctor;

import entity.*;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fish
 */
public class DoctorClient extends javax.swing.JFrame {

    private static final int SERVER_PORT = 10000;
    private boolean connected;
    private Socket requestSocket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    private int doctorId;
    private HistoryDetailInfo patientHistory;
    private Vector listElement;
    private Vector addDrug;
    private Vector addDrugHead;
    private Vector searchDrug;
    private Vector searchDrugHead;

    /**
     * Creates new form DoctorClient
     */
    public DoctorClient() throws UnknownHostException, IOException {
	patientHistory = null;
	listElement = new Vector();
	addDrug = new Vector();
	addDrugHead = new Vector();
	addDrugHead.add("药物号");
	addDrugHead.add("药物");
	addDrugHead.add("数量");
	addDrugHead.add("价格");

	searchDrug = new Vector();
	searchDrugHead = new Vector();
	searchDrugHead.add("药物号");
	searchDrugHead.add("药物");
	searchDrugHead.add("厂商");
	searchDrugHead.add("库存");
	searchDrugHead.add("单价");
	searchDrugHead.add("介绍");

	initComponents();
	requestSocket = new Socket("localhost", SERVER_PORT);
	System.out.println("Connected to localhost in port 2004");
	out = new ObjectOutputStream(requestSocket.getOutputStream());
	out.flush();
	in = new ObjectInputStream(requestSocket.getInputStream());
	out.writeObject("doctor");
	out.flush();
	this.setVisible(false);
	loginWindow.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginWindow = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        doctorIdField = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        viewHistory = new javax.swing.JDialog();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        viewHistoryIdFied = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        viewTimeField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        viewDoctorIdField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewMainField = new javax.swing.JTextArea();
        returnButton = new javax.swing.JButton();
        drugWindow = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        searchDrugTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        needDrugTable = new javax.swing.JTable();
        drugDelete = new javax.swing.JButton();
        drugAdd = new javax.swing.JButton();
        drugReturn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        keywordField = new javax.swing.JTextField();
        infoSearchButton = new javax.swing.JButton();
        nameSearchButton = new javax.swing.JButton();
        loginError = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        loginErrorOk = new javax.swing.JButton();
        sendSuccess = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        sendOk = new javax.swing.JButton();
        noPatientWindow = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        noPatientOk = new javax.swing.JButton();
        logoutError = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        logoutErrorButton = new javax.swing.JButton();
        addDrugWindow = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        addDrugText = new javax.swing.JTextArea();
        addDrugNumField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        addDrugOk = new javax.swing.JButton();
        addDrugCancel = new javax.swing.JButton();
        addDrugId = new javax.swing.JLabel();
        addDrugPrice = new javax.swing.JLabel();
        addDrugName = new javax.swing.JLabel();
        addDrugMaxNum = new javax.swing.JLabel();
        numErrorWindow = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        numErrorOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyInfoField = new javax.swing.JTextArea();
        confirmHistory = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyList = new javax.swing.JList();
        ShowDrug = new javax.swing.JButton();
        IdField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        logout = new javax.swing.JButton();

        loginWindow.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        loginWindow.setTitle("医生登录");
        loginWindow.setBounds(new java.awt.Rectangle(100, 100, 334, 176));
        loginWindow.setResizable(false);

        jLabel5.setText("ID");

        login.setText("登录");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginWindowLayout = new javax.swing.GroupLayout(loginWindow.getContentPane());
        loginWindow.getContentPane().setLayout(loginWindowLayout);
        loginWindowLayout.setHorizontalGroup(
            loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginWindowLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginWindowLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(login)))
                .addGap(57, 57, 57))
        );
        loginWindowLayout.setVerticalGroup(
            loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginWindowLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(doctorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(login)
                .addGap(47, 47, 47))
        );

        viewHistory.setBounds(new java.awt.Rectangle(100, 100, 460, 356));
        viewHistory.setModal(true);
        viewHistory.setResizable(false);

        jLabel6.setText("病历号");

        jLabel7.setText("时间");

        jLabel8.setText("医生ID");

        viewMainField.setColumns(20);
        viewMainField.setRows(5);
        jScrollPane3.setViewportView(viewMainField);

        returnButton.setText("返回");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewHistoryLayout = new javax.swing.GroupLayout(viewHistory.getContentPane());
        viewHistory.getContentPane().setLayout(viewHistoryLayout);
        viewHistoryLayout.setHorizontalGroup(
            viewHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(viewHistoryLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(viewHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewHistoryLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewHistoryIdFied, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewDoctorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewHistoryLayout.createSequentialGroup()
                                .addComponent(returnButton)
                                .addGap(16, 16, 16)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        viewHistoryLayout.setVerticalGroup(
            viewHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewHistoryLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(viewHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(viewHistoryIdFied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(viewTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(viewDoctorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnButton)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        drugWindow.setBounds(new java.awt.Rectangle(100, 100, 714, 480));

        searchDrugTable.setModel(new javax.swing.table.DefaultTableModel(
            searchDrug,
            searchDrugHead
        ));
        searchDrugTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(searchDrugTable);

        needDrugTable.setModel(new javax.swing.table.DefaultTableModel(
            addDrug,
            addDrugHead
        ));
        needDrugTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(needDrugTable);

        drugDelete.setText("删除");
        drugDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugDeleteActionPerformed(evt);
            }
        });

        drugAdd.setText("添加");
        drugAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugAddActionPerformed(evt);
            }
        });

        drugReturn.setText("返回");
        drugReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugReturnActionPerformed(evt);
            }
        });

        jLabel9.setText("关键词");

        infoSearchButton.setText("模糊搜索");
        infoSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoSearchButtonActionPerformed(evt);
            }
        });

        nameSearchButton.setText("精确搜索");
        nameSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drugWindowLayout = new javax.swing.GroupLayout(drugWindow.getContentPane());
        drugWindow.getContentPane().setLayout(drugWindowLayout);
        drugWindowLayout.setHorizontalGroup(
            drugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugWindowLayout.createSequentialGroup()
                .addGroup(drugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drugWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(drugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(drugDelete)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(drugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drugWindowLayout.createSequentialGroup()
                                .addComponent(drugAdd)
                                .addGap(18, 18, 18)
                                .addComponent(drugReturn))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)))
                    .addGroup(drugWindowLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(infoSearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(nameSearchButton)))
                .addGap(32, 32, 32))
        );
        drugWindowLayout.setVerticalGroup(
            drugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drugWindowLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(drugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoSearchButton)
                    .addComponent(nameSearchButton))
                .addGap(21, 21, 21)
                .addGroup(drugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(drugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugDelete)
                    .addComponent(drugAdd)
                    .addComponent(drugReturn))
                .addGap(18, 18, 18))
        );

        loginError.setBackground(java.awt.Color.white);
        loginError.setBounds(new java.awt.Rectangle(100, 100, 302, 164));
        loginError.setModal(true);
        loginError.setUndecorated(true);

        jLabel10.setText("请输入正确的医生号码");

        loginErrorOk.setText("OK");
        loginErrorOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginErrorOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginErrorLayout = new javax.swing.GroupLayout(loginError.getContentPane());
        loginError.getContentPane().setLayout(loginErrorLayout);
        loginErrorLayout.setHorizontalGroup(
            loginErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginErrorLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(loginErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(loginErrorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(loginErrorOk)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        loginErrorLayout.setVerticalGroup(
            loginErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginErrorLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(32, 32, 32)
                .addComponent(loginErrorOk)
                .addGap(41, 41, 41))
        );

        sendSuccess.setBounds(new java.awt.Rectangle(100, 100, 376, 186));
        sendSuccess.setModal(true);
        sendSuccess.setUndecorated(true);

        jLabel11.setText("诊断完成，发送成功");

        sendOk.setText("OK");
        sendOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sendSuccessLayout = new javax.swing.GroupLayout(sendSuccess.getContentPane());
        sendSuccess.getContentPane().setLayout(sendSuccessLayout);
        sendSuccessLayout.setHorizontalGroup(
            sendSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendSuccessLayout.createSequentialGroup()
                .addGroup(sendSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sendSuccessLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel11))
                    .addGroup(sendSuccessLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(sendOk)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        sendSuccessLayout.setVerticalGroup(
            sendSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendSuccessLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(sendOk)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        noPatientWindow.setBounds(new java.awt.Rectangle(100, 100, 375, 185));
        noPatientWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        noPatientWindow.setModal(true);
        noPatientWindow.setUndecorated(true);

        jLabel12.setText("暂时没有病人");

        noPatientOk.setText("OK");
        noPatientOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPatientOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout noPatientWindowLayout = new javax.swing.GroupLayout(noPatientWindow.getContentPane());
        noPatientWindow.getContentPane().setLayout(noPatientWindowLayout);
        noPatientWindowLayout.setHorizontalGroup(
            noPatientWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noPatientWindowLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(noPatientWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(noPatientWindowLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(noPatientOk)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        noPatientWindowLayout.setVerticalGroup(
            noPatientWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noPatientWindowLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(noPatientOk)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        logoutError.setBounds(new java.awt.Rectangle(100, 100, 290, 182));

        jLabel13.setText("请在完成诊断后登出");

        logoutErrorButton.setText("OK");
        logoutErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutErrorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoutErrorLayout = new javax.swing.GroupLayout(logoutError.getContentPane());
        logoutError.getContentPane().setLayout(logoutErrorLayout);
        logoutErrorLayout.setHorizontalGroup(
            logoutErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutErrorLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(logoutErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(logoutErrorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(logoutErrorButton)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        logoutErrorLayout.setVerticalGroup(
            logoutErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutErrorLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutErrorButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        addDrugWindow.setBounds(new java.awt.Rectangle(100, 100, 342, 254));
        addDrugWindow.setModal(true);
        addDrugWindow.setUndecorated(true);

        addDrugText.setColumns(20);
        addDrugText.setRows(5);
        jScrollPane6.setViewportView(addDrugText);

        jLabel14.setText("数量");

        addDrugOk.setText("确定");
        addDrugOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugOkActionPerformed(evt);
            }
        });

        addDrugCancel.setText("取消");
        addDrugCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugCancelActionPerformed(evt);
            }
        });

        addDrugId.setText("as");

        addDrugPrice.setText("jLabel16");

        addDrugName.setText("jLabel16");

        addDrugMaxNum.setText("as");

        javax.swing.GroupLayout addDrugWindowLayout = new javax.swing.GroupLayout(addDrugWindow.getContentPane());
        addDrugWindow.getContentPane().setLayout(addDrugWindowLayout);
        addDrugWindowLayout.setHorizontalGroup(
            addDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDrugWindowLayout.createSequentialGroup()
                .addGroup(addDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addDrugWindowLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addDrugWindowLayout.createSequentialGroup()
                        .addGroup(addDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDrugWindowLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel14)
                                .addGap(35, 35, 35)
                                .addComponent(addDrugNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addDrugWindowLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(addDrugOk)
                                .addGap(39, 39, 39)
                                .addComponent(addDrugCancel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(addDrugWindowLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(addDrugName)
                .addGap(28, 28, 28)
                .addComponent(addDrugPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDrugMaxNum))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDrugWindowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addDrugId)
                .addContainerGap())
        );
        addDrugWindowLayout.setVerticalGroup(
            addDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDrugWindowLayout.createSequentialGroup()
                .addGroup(addDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDrugWindowLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(addDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addDrugPrice)
                            .addComponent(addDrugName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addDrugNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(addDrugWindowLayout.createSequentialGroup()
                        .addComponent(addDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDrugMaxNum)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDrugCancel)
                    .addComponent(addDrugOk))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        numErrorWindow.setBounds(new java.awt.Rectangle(100, 100, 301, 187));
        numErrorWindow.setModal(true);
        numErrorWindow.setUndecorated(true);

        jLabel15.setText("请输入正确的数字");

        numErrorOk.setText("OK");
        numErrorOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numErrorOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout numErrorWindowLayout = new javax.swing.GroupLayout(numErrorWindow.getContentPane());
        numErrorWindow.getContentPane().setLayout(numErrorWindowLayout);
        numErrorWindowLayout.setHorizontalGroup(
            numErrorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numErrorWindowLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(numErrorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(numErrorWindowLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(numErrorOk)))
                .addGap(93, 93, 93))
        );
        numErrorWindowLayout.setVerticalGroup(
            numErrorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numErrorWindowLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addComponent(numErrorOk)
                .addGap(60, 60, 60))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("诊断病人");

        historyInfoField.setColumns(20);
        historyInfoField.setRows(5);
        jScrollPane1.setViewportView(historyInfoField);

        confirmHistory.setText("下一位");
        confirmHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmHistoryActionPerformed(evt);
            }
        });

        jLabel1.setText("姓名");

        jLabel2.setText("ID号");

        nameField.setEditable(false);
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        genderField.setEditable(false);

        jLabel3.setText("性别");

        historyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(historyList);

        ShowDrug.setText("开药");
        ShowDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDrugActionPerformed(evt);
            }
        });

        IdField.setEditable(false);

        jLabel4.setText("年龄");

        ageField.setEditable(false);

        logout.setText("登出");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShowDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(logout)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(ShowDrug)
                        .addGap(18, 18, 18)
                        .addComponent(confirmHistory))
                    .addComponent(jScrollPane1))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
	if (patientHistory == null) {
	    DoctorLogout dl = new DoctorLogout(doctorId);
	    doctorId = -1;
	    sendObject(dl);
	    this.setVisible(false);
	    loginWindow.setVisible(true);
	} else {
	    logoutError.setVisible(true);
	}
    }//GEN-LAST:event_logoutActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
	try {
	    int doctorId = Integer.parseInt(doctorIdField.getText());
	    DoctorLogin dl = new DoctorLogin(doctorId);
	    sendObject(dl);
	    boolean ok = in.readBoolean();
	    if (ok) {
		loginWindow.setVisible(false);
		this.setVisible(true);
		this.doctorId = doctorId;
	    } else {
		loginError.setVisible(true);
	    }
	} catch (IOException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	} catch (NumberFormatException e) {
	    loginError.setVisible(true);
	}
    }//GEN-LAST:event_loginActionPerformed

    private void loginErrorOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginErrorOkActionPerformed
	loginError.setVisible(false);
    }//GEN-LAST:event_loginErrorOkActionPerformed

    private void confirmHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmHistoryActionPerformed
	if (patientHistory == null) {
	    NextPatient np = new NextPatient(doctorId);
	    sendObject(np);
	    try {
		patientHistory = (HistoryDetailInfo) in.readObject();
		if (patientHistory != null) {
		    listElement.clear();
		    for (int i = 0; i < patientHistory.getHistoryList().size(); i++) {
			listElement.add(patientHistory.getHistoryList().get(i));
		    }
		    historyList.setListData(listElement);
		    nameField.setText(patientHistory.getPatientName());
		    IdField.setText(patientHistory.getPatientId());
		    if (patientHistory.getGender()) {
			genderField.setText("男");
		    } else {
			genderField.setText("女");
		    }
		    int age = patientHistory.getAge();
		    ageField.setText(String.valueOf(age));
		    confirmHistory.setText("确定");
		} else {
		    noPatientWindow.setVisible(true);
		}
	    } catch (IOException ex) {
		Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	    } catch (ClassNotFoundException ex) {
		Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	    }
	} else {
	    String str = historyInfoField.getText();
	    patientHistory.setDiseaseInfo(str);
	    sendObject(patientHistory);
	    patientHistory = null;
	    nameField.setText("");
	    IdField.setText("");
	    genderField.setText("");
	    ageField.setText("");
	    listElement.clear();
	    addDrug.clear();
	    searchDrug.clear();
	    historyList.setListData(listElement);
	    confirmHistory.setText("下一位");
	    historyInfoField.setText("");
	    sendSuccess.setVisible(true);
	}
    }//GEN-LAST:event_confirmHistoryActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void sendOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendOkActionPerformed
	sendSuccess.setVisible(false);
    }//GEN-LAST:event_sendOkActionPerformed

    private void noPatientOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPatientOkActionPerformed
	noPatientWindow.setVisible(false);
    }//GEN-LAST:event_noPatientOkActionPerformed

    private void historyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyListMouseClicked
	if (historyList.getSelectedIndex() != -1) {
	    if (evt.getClickCount() == 2) {
		int oldHistoryId = (int) historyList.getSelectedValue();
		GetHistory gh = new GetHistory(oldHistoryId);
		sendObject(gh);
		try {
		    HistoryInfo hi = (HistoryInfo) in.readObject();
		    viewHistoryIdFied.setText(String.valueOf(hi.getHistoryId()));
		    viewTimeField.setText(hi.getTime().toString());
		    viewDoctorIdField.setText(String.valueOf(hi.getDoctorId()));
		    String str = "病历: \n" + hi.getDiseaseInfo();
		    for (int i = 0; i < hi.getDrugs().size(); i++) {
			str += "\n" + hi.getDrugs().get(i).getDrugName() + "              " + hi.getDrugs().get(i).getQuantity();
		    }
		    viewMainField.setText(str);
		    viewHistory.setVisible(true);
		} catch (IOException ex) {
		    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
		    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
		}
	    }
	}
    }//GEN-LAST:event_historyListMouseClicked

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
	viewHistory.setVisible(false);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void ShowDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDrugActionPerformed
	drugWindow.setVisible(true);
    }//GEN-LAST:event_ShowDrugActionPerformed

    private void logoutErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutErrorButtonActionPerformed
	logoutError.setVisible(false);
    }//GEN-LAST:event_logoutErrorButtonActionPerformed

    private void drugReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugReturnActionPerformed
	drugWindow.setVisible(false);
    }//GEN-LAST:event_drugReturnActionPerformed

    private void infoSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoSearchButtonActionPerformed
	String keyword = keywordField.getText();
	SearchDrug sd = new SearchDrug(keyword, 'N');
	sendObject(sd);
	try {
	    List<DrugInfo> result = (List<DrugInfo>) in.readObject();
	    searchDrug.clear();
	    for (int i = 0; i < result.size(); i++) {
		Vector tmp = new Vector();
		tmp.add(result.get(i).getDrugId());
		tmp.add(result.get(i).getDrugName());
		tmp.add(result.get(i).getManufacturer());
		tmp.add(result.get(i).getRemain());
		tmp.add(result.get(i).getPrice());
		tmp.add(result.get(i).getDrugIntro());
		searchDrug.add(tmp);
	    }
	    searchDrugTable.updateUI();
	} catch (IOException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	} catch (ClassNotFoundException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_infoSearchButtonActionPerformed

    private void nameSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchButtonActionPerformed
	String keyword = keywordField.getText();
	SearchDrug sd = new SearchDrug(keyword, 'D');
	sendObject(sd);
	try {
	    List<DrugInfo> result = (List<DrugInfo>) in.readObject();
	    searchDrug.clear();
	    for (int i = 0; i < result.size(); i++) {
		Vector tmp = new Vector();
		tmp.add(result.get(i).getDrugId());
		tmp.add(result.get(i).getDrugName());
		tmp.add(result.get(i).getManufacturer());
		tmp.add(result.get(i).getRemain());
		tmp.add(result.get(i).getPrice());
		tmp.add(result.get(i).getDrugIntro());
		searchDrug.add(tmp);
	    }
	    searchDrugTable.updateUI();
	} catch (IOException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	} catch (ClassNotFoundException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_nameSearchButtonActionPerformed

    private void drugAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugAddActionPerformed
	addDrugId.setText(searchDrugTable.getValueAt(searchDrugTable.getSelectedRow(), 0).toString());
	addDrugId.setVisible(false);
	addDrugMaxNum.setText(searchDrugTable.getValueAt(searchDrugTable.getSelectedRow(), 3).toString());
	addDrugMaxNum.setVisible(false);
	addDrugNumField.setText("");
	addDrugText.setText("");
	addDrugName.setText(searchDrugTable.getValueAt(searchDrugTable.getSelectedRow(), 1).toString());
	addDrugName.setVisible(true);
	addDrugPrice.setText(searchDrugTable.getValueAt(searchDrugTable.getSelectedRow(), 4).toString());
	addDrugWindow.setVisible(true);
    }//GEN-LAST:event_drugAddActionPerformed

    private void addDrugOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugOkActionPerformed
	try {
	    int maxNum = Integer.parseInt(addDrugMaxNum.getText());
	    int num = Integer.parseInt(addDrugNumField.getText());
	    String drugName = addDrugName.getText();
	    String howToEat = addDrugText.getText();
	    int drugId = Integer.parseInt(addDrugId.getText());
	    int price = Integer.parseInt(addDrugPrice.getText()) * num;
	    if (num <= maxNum) {
		patientHistory.addDrugs(drugId, drugName, "", "", num, howToEat, 'a', price);
		addDrugWindow.setVisible(false);
		Vector tmp = new Vector();
		tmp.add(drugId);
		tmp.add(drugName);
		tmp.add(num);
		tmp.add(price);
		addDrug.add(tmp);
		needDrugTable.updateUI();
	    } else {
		numErrorWindow.setVisible(true);
	    }


	} catch (NumberFormatException e) {
	    numErrorWindow.setVisible(true);
	}
    }//GEN-LAST:event_addDrugOkActionPerformed

    private void addDrugCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugCancelActionPerformed
	addDrugWindow.setVisible(false);
    }//GEN-LAST:event_addDrugCancelActionPerformed

    private void numErrorOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numErrorOkActionPerformed
	numErrorWindow.setVisible(false);
    }//GEN-LAST:event_numErrorOkActionPerformed

    private void drugDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugDeleteActionPerformed
	int drugId = Integer.parseInt(needDrugTable.getValueAt(needDrugTable.getSelectedRow(), 0).toString());
	patientHistory.removeDrug(drugId);
	int index = needDrugTable.getSelectedRow();
	addDrug.remove(index);
	needDrugTable.updateUI();
    }//GEN-LAST:event_drugDeleteActionPerformed

    public void sendString(String input) {
	try {
	    EntityTable e = new EntityTable();
	    e.setType(input);
	    out.writeObject(e);
	    out.flush();
	} catch (IOException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	}

    }

    public void sendObject(Object input) {
	try {
	    out.writeObject(input);
	    out.flush();
	} catch (IOException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	}

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(DoctorClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(DoctorClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(DoctorClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(DoctorClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		try {
		    new DoctorClient();
		} catch (UnknownHostException ex) {
		    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IOException ex) {
		    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
		}
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdField;
    private javax.swing.JButton ShowDrug;
    private javax.swing.JButton addDrugCancel;
    private javax.swing.JLabel addDrugId;
    private javax.swing.JLabel addDrugMaxNum;
    private javax.swing.JLabel addDrugName;
    private javax.swing.JTextField addDrugNumField;
    private javax.swing.JButton addDrugOk;
    private javax.swing.JLabel addDrugPrice;
    private javax.swing.JTextArea addDrugText;
    private javax.swing.JDialog addDrugWindow;
    private javax.swing.JTextField ageField;
    private javax.swing.JButton confirmHistory;
    private javax.swing.JTextField doctorIdField;
    private javax.swing.JButton drugAdd;
    private javax.swing.JButton drugDelete;
    private javax.swing.JButton drugReturn;
    private javax.swing.JDialog drugWindow;
    private javax.swing.JTextField genderField;
    private javax.swing.JTextArea historyInfoField;
    private javax.swing.JList historyList;
    private javax.swing.JButton infoSearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField keywordField;
    private javax.swing.JButton login;
    private javax.swing.JDialog loginError;
    private javax.swing.JButton loginErrorOk;
    private javax.swing.JFrame loginWindow;
    private javax.swing.JButton logout;
    private javax.swing.JDialog logoutError;
    private javax.swing.JButton logoutErrorButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton nameSearchButton;
    private javax.swing.JTable needDrugTable;
    private javax.swing.JButton noPatientOk;
    private javax.swing.JDialog noPatientWindow;
    private javax.swing.JButton numErrorOk;
    private javax.swing.JDialog numErrorWindow;
    private javax.swing.JButton returnButton;
    private javax.swing.JTable searchDrugTable;
    private javax.swing.JButton sendOk;
    private javax.swing.JDialog sendSuccess;
    private javax.swing.JTextField viewDoctorIdField;
    private javax.swing.JDialog viewHistory;
    private javax.swing.JTextField viewHistoryIdFied;
    private javax.swing.JTextArea viewMainField;
    private javax.swing.JTextField viewTimeField;
    // End of variables declaration//GEN-END:variables
}
