/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package deliver;

import doctor.DoctorClient;
import entity.*;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fish
 */
public class DeliverClient extends javax.swing.JFrame {

    private static final int SERVER_PORT = 10000;
    private boolean connected;
    private Socket requestSocket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    private List<HistoryInfo> historyList;
    Vector listElement;
    Vector tableHead;
    Vector tableElement;
    Vector searchTableElement;
    Vector searchTableHead;

    private class HistoryIdUpdate extends Thread {

	private static final int SERVER_PORT = 10000;
	private boolean connected;
	private Socket requestSocket;
	private ObjectOutputStream out;
	private ObjectInputStream in;

	public HistoryIdUpdate() throws UnknownHostException, IOException {
	    requestSocket = new Socket("localhost", SERVER_PORT);
	    System.out.println("Connected to localhost in port 2004");
	    out = new ObjectOutputStream(requestSocket.getOutputStream());
	    out.flush();
	    in = new ObjectInputStream(requestSocket.getInputStream());
	    out.writeObject("chemistUpdate");
	    out.flush();
	    start();
	}

	public void run() {
	    try {
		while (true) {
		    EntityTable e = (EntityTable) in.readObject();
		    if (e.getType().equals("update")) {
			historyList.clear();
			listElement.clear();
			while (true) {
			    EntityTable e1 = (EntityTable) in.readObject();
			    if (e1.getType().equals("end")) {
				break;
			    } else if (e1.getType().equals("HistoryInfo")) {
				HistoryInfo hi = (HistoryInfo) e1;
				historyList.add(hi);
				listElement.add(hi.getHistoryId());
			    }
			}
			historyIdList.setListData(listElement);
			historyIdList.updateUI();
		    }
		    historyIdList.setSelectedIndex(-1);
		}
	    } catch (IOException ex) {
		Logger.getLogger(DeliverClient.class.getName()).log(Level.SEVERE, null, ex);
	    } catch (ClassNotFoundException ex) {
		Logger.getLogger(DeliverClient.class.getName()).log(Level.SEVERE, null, ex);
	    }
	}
    }

    /**
     * Creates new form DeliverClient
     */
    public DeliverClient() throws UnknownHostException, IOException {
	historyList = new ArrayList<>();
	listElement = new Vector();
	tableElement = new Vector();
	tableHead = new Vector();
	tableHead.add("药物ID");
	tableHead.add("药物名称");
	tableHead.add("数量");

	searchTableElement = new Vector();
	searchTableHead = new Vector();
	searchTableHead.add("药物ID");
	searchTableHead.add("药物名称");
	searchTableHead.add("厂商");
	searchTableHead.add("库存");
	searchTableHead.add("价格");
	searchTableHead.add("介绍");

	initComponents();
	requestSocket = new Socket("localhost", SERVER_PORT);
	System.out.println("Connected to localhost in port 2004");
	out = new ObjectOutputStream(requestSocket.getOutputStream());
	out.flush();
	in = new ObjectInputStream(requestSocket.getInputStream());
	out.writeObject("chemist");
	out.flush();

	new HistoryIdUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageDrugWindow = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchDrugTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        keywordField = new javax.swing.JTextField();
        searchDrugButton = new javax.swing.JButton();
        deleteDrugB = new javax.swing.JButton();
        addRemainB = new javax.swing.JButton();
        detailSearchButton = new javax.swing.JButton();
        addDrugButton = new javax.swing.JButton();
        drugReturn = new javax.swing.JButton();
        alarmWindow = new javax.swing.JDialog();
        alarmText = new javax.swing.JLabel();
        alarmOk = new javax.swing.JButton();
        addNewDrugWindow = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        addDrugName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addDrugManufacturer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addDrugPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addDrugInfo = new javax.swing.JTextArea();
        addDrugOk = new javax.swing.JButton();
        addDrugReturn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        addDrugNum = new javax.swing.JTextField();
        addRemainWindow = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        addRemainDrugId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addRemainNum = new javax.swing.JTextField();
        addRemainOk = new javax.swing.JButton();
        addRemainReturn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliverTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        historyIdList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();

        manageDrugWindow.setTitle("药物管理");
        manageDrugWindow.setBounds(new java.awt.Rectangle(100, 100, 730, 475));
        manageDrugWindow.setModal(true);
        manageDrugWindow.setResizable(false);

        searchDrugTable.setModel(new javax.swing.table.DefaultTableModel(
            searchTableElement,
            searchTableHead
        ));
        jScrollPane2.setViewportView(searchDrugTable);

        jLabel1.setText("关键词");

        searchDrugButton.setText("模糊搜索");
        searchDrugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDrugButtonActionPerformed(evt);
            }
        });

        deleteDrugB.setText("删除药物");
        deleteDrugB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDrugBActionPerformed(evt);
            }
        });

        addRemainB.setText("添加库存");
        addRemainB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRemainBActionPerformed(evt);
            }
        });

        detailSearchButton.setText("精确搜索");
        detailSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailSearchButtonActionPerformed(evt);
            }
        });

        addDrugButton.setText("新增药物");
        addDrugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugButtonActionPerformed(evt);
            }
        });

        drugReturn.setText("返回");
        drugReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageDrugWindowLayout = new javax.swing.GroupLayout(manageDrugWindow.getContentPane());
        manageDrugWindow.getContentPane().setLayout(manageDrugWindowLayout);
        manageDrugWindowLayout.setHorizontalGroup(
            manageDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageDrugWindowLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(manageDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageDrugWindowLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageDrugWindowLayout.createSequentialGroup()
                        .addComponent(drugReturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addDrugButton)
                        .addGap(18, 18, 18)
                        .addComponent(addRemainB)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDrugB)
                        .addGap(40, 40, 40))))
            .addGroup(manageDrugWindowLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(searchDrugButton)
                .addGap(18, 18, 18)
                .addComponent(detailSearchButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        manageDrugWindowLayout.setVerticalGroup(
            manageDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageDrugWindowLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(manageDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDrugButton)
                    .addComponent(detailSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(manageDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageDrugWindowLayout.createSequentialGroup()
                        .addGroup(manageDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteDrugB)
                            .addComponent(addRemainB)
                            .addComponent(addDrugButton))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageDrugWindowLayout.createSequentialGroup()
                        .addComponent(drugReturn)
                        .addGap(20, 20, 20))))
        );

        alarmWindow.setBounds(new java.awt.Rectangle(100, 100, 324, 184));
        alarmWindow.setModal(true);
        alarmWindow.setResizable(false);

        alarmText.setText("jLabel3");

        alarmOk.setText("OK");
        alarmOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarmOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alarmWindowLayout = new javax.swing.GroupLayout(alarmWindow.getContentPane());
        alarmWindow.getContentPane().setLayout(alarmWindowLayout);
        alarmWindowLayout.setHorizontalGroup(
            alarmWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarmWindowLayout.createSequentialGroup()
                .addGroup(alarmWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alarmWindowLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(alarmOk))
                    .addGroup(alarmWindowLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(alarmText)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        alarmWindowLayout.setVerticalGroup(
            alarmWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alarmWindowLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(alarmText)
                .addGap(18, 18, 18)
                .addComponent(alarmOk)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        addNewDrugWindow.setTitle("新增药物");
        addNewDrugWindow.setBounds(new java.awt.Rectangle(100, 100, 388, 426));
        addNewDrugWindow.setModal(true);
        addNewDrugWindow.setResizable(false);

        jLabel3.setText("名称");

        jLabel4.setText("厂商");

        jLabel5.setText("单价");

        jLabel6.setText("介绍");

        addDrugInfo.setColumns(20);
        addDrugInfo.setRows(5);
        jScrollPane4.setViewportView(addDrugInfo);

        addDrugOk.setText("新增");
        addDrugOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugOkActionPerformed(evt);
            }
        });

        addDrugReturn.setText("返回");
        addDrugReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugReturnActionPerformed(evt);
            }
        });

        jLabel7.setText("数量");

        javax.swing.GroupLayout addNewDrugWindowLayout = new javax.swing.GroupLayout(addNewDrugWindow.getContentPane());
        addNewDrugWindow.getContentPane().setLayout(addNewDrugWindowLayout);
        addNewDrugWindowLayout.setHorizontalGroup(
            addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewDrugWindowLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addNewDrugWindowLayout.createSequentialGroup()
                        .addComponent(addDrugReturn)
                        .addGap(18, 18, 18)
                        .addComponent(addDrugOk))
                    .addGroup(addNewDrugWindowLayout.createSequentialGroup()
                        .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewDrugWindowLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addDrugManufacturer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addDrugName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addNewDrugWindowLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(addDrugPrice)
                                    .addComponent(addDrugNum))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        addNewDrugWindowLayout.setVerticalGroup(
            addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewDrugWindowLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addDrugManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addDrugPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addDrugNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addNewDrugWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDrugOk)
                    .addComponent(addDrugReturn))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        addRemainWindow.setTitle("增加库存");
        addRemainWindow.setBounds(new java.awt.Rectangle(100, 100, 263, 208));
        addRemainWindow.setModal(true);
        addRemainWindow.setResizable(false);

        jLabel8.setText("药物ID");

        addRemainDrugId.setEditable(false);

        jLabel9.setText("数量");

        addRemainOk.setText("确定");
        addRemainOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRemainOkActionPerformed(evt);
            }
        });

        addRemainReturn.setText("返回");
        addRemainReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRemainReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addRemainWindowLayout = new javax.swing.GroupLayout(addRemainWindow.getContentPane());
        addRemainWindow.getContentPane().setLayout(addRemainWindowLayout);
        addRemainWindowLayout.setHorizontalGroup(
            addRemainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRemainWindowLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(addRemainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRemainWindowLayout.createSequentialGroup()
                        .addComponent(addRemainReturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addRemainOk)
                        .addGap(25, 25, 25))
                    .addGroup(addRemainWindowLayout.createSequentialGroup()
                        .addGroup(addRemainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(addRemainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addRemainNum)
                            .addComponent(addRemainDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        addRemainWindowLayout.setVerticalGroup(
            addRemainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRemainWindowLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(addRemainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addRemainDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addRemainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addRemainNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addRemainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRemainOk)
                    .addComponent(addRemainReturn))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("药物发放");

        deliverTable.setModel(new javax.swing.table.DefaultTableModel(
            tableElement,
            tableHead
        ));
        deliverTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(deliverTable);

        jButton1.setText("完成");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("删除");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("管理药物");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        historyIdList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                historyIdListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(historyIdList);

        jLabel2.setText("病历ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historyIdListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_historyIdListValueChanged
	if (historyIdList.getSelectedIndex() != -1) {
	    HistoryInfo hi = null;
	    int historyId = Integer.parseInt(historyIdList.getSelectedValue().toString());
	    for (int i = 0; i < historyList.size(); i++) {
		if (historyId == historyList.get(i).getHistoryId()) {
		    hi = historyList.get(i);
		    break;
		}
	    }
	    if (hi != null) {
		tableElement.clear();
		for (int i = 0; i < hi.getDrugs().size(); i++) {
		    Vector tmp = new Vector();
		    tmp.add(hi.getDrugs().get(i).getDrugId());
		    tmp.add(hi.getDrugs().get(i).getDrugName());
		    tmp.add(hi.getDrugs().get(i).getQuantity());
		    tableElement.add(tmp);
		}
		deliverTable.updateUI();
	    }
	}
    }//GEN-LAST:event_historyIdListValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	if (historyIdList.getSelectedIndex() != -1) {
	    int historyId = Integer.parseInt(historyIdList.getSelectedValue().toString());
	    CompleteHistory ch = new CompleteHistory(historyId);
	    sendObject(ch);
	    tableElement.clear();
	    deliverTable.updateUI();
	    alarmText.setText("完成");
	    alarmWindow.setVisible(true);
	} else {
	    alarmText.setText("请选择病历");
	    alarmWindow.setVisible(true);
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void alarmOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarmOkActionPerformed
	alarmWindow.setVisible(false);
    }//GEN-LAST:event_alarmOkActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	manageDrugWindow.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void drugReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugReturnActionPerformed
	manageDrugWindow.setVisible(false);
    }//GEN-LAST:event_drugReturnActionPerformed

    private void searchDrugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDrugButtonActionPerformed
	String keyword = keywordField.getText();
	SearchDrug sd = new SearchDrug(keyword, 'N');
	sendObject(sd);
	try {
	    List<DrugInfo> result = (List<DrugInfo>) in.readObject();
	    searchTableElement.clear();
	    for (int i = 0; i < result.size(); i++) {
		Vector tmp = new Vector();
		tmp.add(result.get(i).getDrugId());
		tmp.add(result.get(i).getDrugName());
		tmp.add(result.get(i).getManufacturer());
		tmp.add(result.get(i).getRemain());
		tmp.add(result.get(i).getPrice());
		tmp.add(result.get(i).getDrugIntro());
		searchTableElement.add(tmp);
	    }
	    searchDrugTable.updateUI();
	} catch (IOException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	} catch (ClassNotFoundException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_searchDrugButtonActionPerformed

    private void detailSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailSearchButtonActionPerformed
	String keyword = keywordField.getText();
	SearchDrug sd = new SearchDrug(keyword, 'D');
	sendObject(sd);
	try {
	    List<DrugInfo> result = (List<DrugInfo>) in.readObject();
	    searchTableElement.clear();
	    for (int i = 0; i < result.size(); i++) {
		Vector tmp = new Vector();
		tmp.add(result.get(i).getDrugId());
		tmp.add(result.get(i).getDrugName());
		tmp.add(result.get(i).getManufacturer());
		tmp.add(result.get(i).getRemain());
		tmp.add(result.get(i).getPrice());
		tmp.add(result.get(i).getDrugIntro());
		searchTableElement.add(tmp);
	    }
	    searchDrugTable.updateUI();
	} catch (IOException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	} catch (ClassNotFoundException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_detailSearchButtonActionPerformed

    private void deleteDrugBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDrugBActionPerformed
	if (searchDrugTable.getSelectedRow() != -1) {
	    try {
		int drugId = Integer.parseInt(searchDrugTable.getValueAt(searchDrugTable.getSelectedRow(), 0).toString());
		DeleteDrug dd = new DeleteDrug(drugId);
		sendObject(dd);
		searchTableElement.remove(searchDrugTable.getSelectedRow());
		searchDrugTable.updateUI();
	    } catch (NumberFormatException e) {
		alarmText.setText("请选择正确的行");
		alarmWindow.setVisible(true);
	    }
	}
    }//GEN-LAST:event_deleteDrugBActionPerformed

    private void addRemainBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRemainBActionPerformed
	if (searchDrugTable.getSelectedRow() != -1) {
	    try {
		String drugId = searchDrugTable.getValueAt(searchDrugTable.getSelectedRow(), 0).toString();
		addRemainDrugId.setText(drugId);
		addRemainNum.setText("");
		addRemainWindow.setVisible(true);
	    } catch (NumberFormatException e) {
		alarmText.setText("请选择正确的行");
		alarmWindow.setVisible(true);
	    }
	}
    }//GEN-LAST:event_addRemainBActionPerformed

    private void addDrugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugButtonActionPerformed
	addDrugName.setText("");
	addDrugManufacturer.setText("");
	addDrugInfo.setText("");
	addDrugPrice.setText("");
	addDrugNum.setText("");
	addNewDrugWindow.setVisible(true);
    }//GEN-LAST:event_addDrugButtonActionPerformed

    private void addDrugReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugReturnActionPerformed
	addNewDrugWindow.setVisible(false);
    }//GEN-LAST:event_addDrugReturnActionPerformed

    private void addDrugOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugOkActionPerformed
	try {
	    String drugName = addDrugName.getText();
	    String drugManufacturer = addDrugManufacturer.getText();
	    String drugInfo = addDrugInfo.getText();
	    int price = Integer.parseInt(addDrugPrice.getText());
	    int num = Integer.parseInt(addDrugNum.getText());
	    AddNewDrug ad = new AddNewDrug(drugName, drugInfo, drugManufacturer, price, num);
	    sendObject(ad);
	    addNewDrugWindow.setVisible(false);
	} catch (NumberFormatException e) {
	    alarmText.setText("请输入正确的格式");
	    alarmWindow.setVisible(true);
	}

    }//GEN-LAST:event_addDrugOkActionPerformed

    private void addRemainReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRemainReturnActionPerformed
	addRemainWindow.setVisible(false);
    }//GEN-LAST:event_addRemainReturnActionPerformed

    private void addRemainOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRemainOkActionPerformed
	try {
	    int drugId = Integer.parseInt(addRemainDrugId.getText());
	    int num = Integer.parseInt(addRemainNum.getText());
	    AddRemain ar = new AddRemain(drugId, num);
	    sendObject(ar);
	    addRemainWindow.setVisible(false);
	} catch (NumberFormatException e) {
	    alarmText.setText("请输入正确的格式");
	    alarmWindow.setVisible(true);
	}
    }//GEN-LAST:event_addRemainOkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	if (historyIdList.getSelectedIndex() != -1) {
	    int historyId = Integer.parseInt(historyIdList.getSelectedValue().toString());
	    NotCompleteHistory nch = new NotCompleteHistory(historyId);
	    sendObject(nch);
	    tableElement.clear();
	    alarmText.setText("删除成功");
	    alarmWindow.setVisible(true);
	} else {
	    alarmText.setText("请选择病历");
	    alarmWindow.setVisible(true);
	}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void sendString(String input) {
	try {
	    EntityTable e = new EntityTable();
	    e.setType(input);
	    out.writeObject(e);
	    out.flush();
	} catch (IOException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	}

    }

    public void sendObject(Object input) {
	try {
	    out.writeObject(input);
	    out.flush();
	} catch (IOException ex) {
	    Logger.getLogger(DoctorClient.class.getName()).log(Level.SEVERE, null, ex);
	}

    }

    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(DeliverClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(DeliverClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(DeliverClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(DeliverClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		try {
		    new DeliverClient().setVisible(true);
		} catch (UnknownHostException ex) {
		    Logger.getLogger(DeliverClient.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IOException ex) {
		    Logger.getLogger(DeliverClient.class.getName()).log(Level.SEVERE, null, ex);
		}
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrugButton;
    private javax.swing.JTextArea addDrugInfo;
    private javax.swing.JTextField addDrugManufacturer;
    private javax.swing.JTextField addDrugName;
    private javax.swing.JTextField addDrugNum;
    private javax.swing.JButton addDrugOk;
    private javax.swing.JTextField addDrugPrice;
    private javax.swing.JButton addDrugReturn;
    private javax.swing.JDialog addNewDrugWindow;
    private javax.swing.JButton addRemainB;
    private javax.swing.JTextField addRemainDrugId;
    private javax.swing.JTextField addRemainNum;
    private javax.swing.JButton addRemainOk;
    private javax.swing.JButton addRemainReturn;
    private javax.swing.JDialog addRemainWindow;
    private javax.swing.JButton alarmOk;
    private javax.swing.JLabel alarmText;
    private javax.swing.JDialog alarmWindow;
    private javax.swing.JButton deleteDrugB;
    private javax.swing.JTable deliverTable;
    private javax.swing.JButton detailSearchButton;
    private javax.swing.JButton drugReturn;
    private javax.swing.JList historyIdList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField keywordField;
    private javax.swing.JDialog manageDrugWindow;
    private javax.swing.JButton searchDrugButton;
    private javax.swing.JTable searchDrugTable;
    // End of variables declaration//GEN-END:variables
}
